[project]
name = "final-chatbot"
version = "0.1.0"
description = "Agentic Langgraph workflow"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=1.3.14",
    "langchain-chroma>=1.1.0",
    "langchain-groq>=1.1.3",
    "langchain-huggingface[full]>=1.2.2",
    "langchain-text-splitters>=1.1.2",
    "langchain-unstructured>=1.0.1",
    "langgraph>=1.2.10",
    "langgraph-checkpoint-sqlite>=3.1.1",
    "streamlit>=1.60.0",
    "tavily>=1.1.0",
    "tavily-python>=0.7.27",
    "torchvision>=0.28.0",
]
